name: default
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - jupyter
    - ipython
    - nb_conda
    - matplotlib
    - xarray
    - netcdf4
    - cartopy
    - pyjokes
