name: default
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy=1.16
    - scipy=1.2
    - jupyter
    - nb_conda=2.2
    - matplotlib=3.0
    - conda-smithy
    - conda-forge-pinning
